name: artic_minion
description: |
  Run the alignment/variant-call/consensus logic of the artic pipeline
keywords:
  - artic
  - aggregate
  - demultiplexed reads
tools:
  - artic:
      description: ARTIC pipeline - a bioinformatics pipeline for working with
        virus sequencing data sequenced with nanopore
      homepage: https://artic.readthedocs.io/en/latest/
      documentation: https://artic.readthedocs.io/en/latest/
      tool_dev_url: https://github.com/artic-network/fieldbioinformatics
      licence: ["MIT"]
      identifier: biotools:artic
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: FastQ file containing reads
        pattern: "*.{fastq.gz}"
        ontologies: []
  - fast5_dir:
      type: directory
      description: Directory containing raw FAST5 files
      pattern: "*"
  - sequencing_summary:
      type: file
      description: Sequencing summary file from Guppy
      pattern: "*.txt"
  - primer-schemes/${scheme}/V${scheme_version}/${scheme}.reference.fasta:
      type: file
      description: Reference FASTA file for ARTIC primer scheme
      pattern: "*.fasta"
  - primer-schemes/${scheme}/V${scheme_version}/${scheme}.scheme.bed:
      type: file
      description: BED file for ARTIC primer scheme
      pattern: "*.bed"
  - medaka_model_file:
      type: file
      description: File containing Medaka model to be used (if provided)
      pattern: "*"
  - medaka_model_string:
      type: string
      description: Medaka model name string (used if file not provided)
  - scheme:
      type: string
      description: ARTIC primer scheme name
  - scheme_version:
      type: string
      description: ARTIC primer scheme version
output:
  results:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.*:
          type: file
          description: Aggregated FastQ files
          pattern: "*.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.sorted.bam:
          type: file
          description: BAM file
          pattern: "*.{sorted.bam}"
          ontologies: []
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.sorted.bam.bai:
          type: file
          description: BAM index file
          pattern: "*.{sorted.bai}"
          ontologies: []
  bam_trimmed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.trimmed.rg.sorted.bam:
          type: file
          description: BAM file with the primers left on
          pattern: "*.{trimmed.rg.sorted.bam}"
          ontologies: []
  bai_trimmed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.trimmed.rg.sorted.bam.bai:
          type: file
          description: BAM index file of bam_trimmed
          pattern: "*.{sorted.bai}"
          ontologies: []
  bam_primertrimmed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.primertrimmed.rg.sorted.bam:
          type: file
          description: BAM containing reads after primer-binding site trimming
          pattern: "*.{trimmed.rg.sorted.bam}"
          ontologies: []
  bai_primertrimmed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.primertrimmed.rg.sorted.bam.bai:
          type: file
          description: BAM index file of bam_primertrimmed
          pattern: "*.{primertrimmed.rg.sorted.bam.bai}"
          ontologies: []
  fasta:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.consensus.fasta:
          type: file
          description: FAST file with consensus sequence
          pattern: "*.{consensus.fasta}"
          ontologies: []
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.pass.vcf.gz:
          type: file
          description: VCF file containing detected variants passing quality
            filter
          pattern: "*.{pass.vcf.gz}"
          ontologies: []
  tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.pass.vcf.gz.tbi:
          type: file
          description: VCF index
          pattern: "*.{pass.vcf.gz.tbi}"
          ontologies: []
  json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.json":
          type: file
          description: JSON file for MultiQC
          pattern: "*.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@joseespinosa"
  - "@drpatelh"
maintainers:
  - "@joseespinosa"
  - "@drpatelh"
