# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_trim_primers_ivar"
description: Perform amplicon primer trimming with iVar
keywords:
  - amplicon
  - primer
  - trimming
  - ivar
components:
  - ivar/trim
  - bam_sort_stats_samtools
input:
  - bam:
      description: |
        Mapping BAM files and their index files
        Structure: [ val(meta), [ bam ], [bai] ]
  - bed:
      description: |
        BED file with amplicon primer positions
        Structure: [ path(bed) ]
  - fasta:
      description: |
        Reference genome fasta file
        Structure: [ path(fasta) ]
output:
  - bam_orig:
      type: file
      description: |
        BAM file with primers positions softclipped
        Structure: [ val(meta), bam ]
      pattern: "*.{bam}"
  - log_out:
      type: file
      description: |
        Output log file
        Structure: [ val(meta), log ]
  - bam:
      type: file
      description: |
        Sorted BAM file with primers positions softclipped
        Structure: [ val(meta), [ bam ] ]
      pattern: "*.{bam}"
  - bai:
      type: file
      description: |
        Sorted BAM index file
        Structure: [ val(meta), [ bai ] ]
      pattern: "*.{bai}"
  - csi:
      type: file
      description: |
        coordinate sorted index file
        Structure: [ val(meta), [ csi ] ]
  - stats:
      type: file
      description: File containing samtools stats output
      pattern: "*.{stats}"
  - flagstat:
      type: file
      description: File containing samtools flagstat output
      pattern: "*.{flagstat}"
  - idxstats:
      type: file
      description: File containing samtools idxstats output
      pattern: "*.{idxstats}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
maintainers:
  - "@svarona"
  - "@saramonzon"
