# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "assembly_qc"
description: Perform quality control on de novo assembly
keywords:
  - assembly
  - quality_control
  - fasta
components:
  - filter/blastn
  - abacas
  - blast/blastn
  - plasmidid
  - quast
input:
  - scaffolds:
      description: |
        Scaffolds from de novo assembly
        Structure: [ val(meta), [ scaffolds ] ]
  - fasta:
      description: |
        Index of the reference genome fasta file
        Structure: [ path(fasta) ]
  - gff:
      description: |
        GFF file of the reference genome
        Structure: [ path(gff) ]
  - blast_db:
      description: |
        BLAST database to perform the alignment
        Structure: [ path(blast_db) ]
  - blast_header:
      description: |
        Header for the BLAST results
        Structure: [ path(blast_header) ]
  - blast_filtered_header:
      description: |
        Header for the filtered BLAST results
        Structure: [ path(blast_filtered_header) ]
output:
  - blast_txt:
      description: |
        Results of the BLAST alignment
        Structure: [ val(meta), [ txt ] ]
  - blast_filter_txt:
      description: |
        Filtered results of the  BLAST alignment
        Structure: [ val(meta), [ txt ] ]
  - quast_results:
      description: |
        Results of the quast quality control
        Structure: [ val(meta), [ results ] ]
  - quast_tsv:
      description: |
        TSV report with QUAST results
        Structure: [ val(meta), [ tsv ] ]
  - abacas_results:
      description: |
        Sequence fasta file of ABACAS contiguation analysis
        Structure: [ val(meta), [ results ] ]
  - plasmidid_html:
      description: |
        HTML report with PlasmidID results
        Structure: [ val(meta), [ html ] ]
  - plasmidid_tab:
      description: |
        TAB report with PlasmidID results
        Structure:  [ val(meta), [ tab ] ]
  - plasmidid_images:
      description: |
        Circos images of PlasmidID results
        Structure: [ val(meta), [ images/ ] ]
  - plasmidid_logs:
      description: |
        Logs from PlasmidID analysis
        Structure: [ val(meta), [ logs/ ] ]
  - plasmidid_data:
      description: |
        Data files from PlasmidID analysis
        Structure: [ val(meta), [ data/ ] ]
  - plasmidid_database:
      description: |
        Database data from PlasmidID analysis
        Structure:  [ val(meta), [ database/ ] ]
  - plasmidid_fasta:
      description: |
        Fasta files from PlasmidID analysis
        Structure: [ val(meta), [ fasta_files/ ] ]
  - plasmidid_kmer:
      description: |
        Kmer folder from PlasmidID analysis
        Structure: [ val(meta), [ kmer/ ] ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@drpatelh"
maintainers:
  - "@svarona"
  - "@saramonzon"
