---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.2.0
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-ggplot2=3.5.1
  - conda-forge::r-scales=1.3.0
  - conda-forge::r-viridis=0.6.5
  - conda-forge::r-tidyverse=1.3.2
  - bioconda::bioconductor-biostrings=2.66.0
  - bioconda::bioconductor-complexheatmap=2.14
