# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "pipeline_initialisation"
description: Subworkflow with functionality specific to the nf-core/viralrecon pipeline
keywords:
  - utils
  - pipeline
  - plugin
components:
  - utils_nfschema_plugin
  - utils_nfcore_pipeline
  - completionemail
  - completionsummary
  - imnotification
  - utils_nextflow_pipeline
input:
  - version:
      type: boolean
      description: Whether to include version information
  - validate_params:
      type: boolean
      description: Boolean whether to validate parameters against the schema at runtime
  - monochrome_logs:
      type: boolean
      description: Do not use coloured log outputs
  - nextflow_cli_args:
      type: array
      description: List of positional nextflow CLI args
  - outdir:
      type: string
      description: The output directory where the results will be saved
  - input:
      type: string
      description: Path to input samplesheet
output:
  - samplesheet:
      type: file
      description: samplesheet CSV file
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@drpatelh"
maintainers:
  - "@svarona"
  - "@saramonzon"
